### ISSUE TITLE
[1] API server certificate not valid for public IP

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-kubespray#24]
When following the instructions in the readme and setting up a cluster on openstack, the API server certificate is reported as invalid when trying to use it with the public IP. The certificate is only valid for the private IP.

**Comment by cristiklein** [comment]
This is dealt with via the `supplementary_addresses_in_ssl_keys` value (see [documentation](https://github.com/kubernetes-sigs/kubespray/blob/master/inventory/sample/group_vars/k8s-cluster/k8s-cluster.yml#L255)). Since this is supposed to be equal to a DNS record that points to the IP address of the load-balancer fronting the masters (or the first master directly), I am unsure this can be easily automated.

**Comment by lentzi90** [comment]
Hmm I was expecting it to be configured through [these variables](https://kubespray.io/#/docs/vars?id=addressing-variables). Anyway, since we know the public IP of all the nodes it shouldn't be a big deal to set these up in the inventory. I think that the dynamic inventories used in some of the `contrib/terraform` examples already do this, but our static `intenctory.ini` file does not.

**Comment by cristiklein** [comment]
Nice find @lentzi90 ! Let's prioritize this.

**Comment by Xartos** [comment]
What statuc `inventory.ini` are you talking about? If you use the static `inventory.ini` files generated by either exoscale or gcp this is set.
https://github.com/kubernetes-sigs/kubespray/blob/master/contrib/terraform/exoscale/templates/inventory.tpl#L9
https://github.com/kubernetes-sigs/kubespray/blob/master/contrib/terraform/gcp/generate-inventory.sh#L60

**Comment by lentzi90** [comment]
I'm talking about [this](https://github.com/elastisys/compliantkubernetes-kubespray/blob/main/config/inventory.ini) that we generate when running init. Openstack doesn't generate an `inventory.ini` file to use, but instead it has the dynamic [terraform.py](https://github.com/kubernetes-sigs/kubespray/blob/75d648cae53eb6b83acb9b75b868ea29eec480d3/contrib/terraform/openstack/hosts). I think we could use that one instead if we just document how. In any case I think it would make sense to add a bit more to our `inventory.ini` to make it useful in other situations like bare metal. :slightly_smiling_face:

**Comment by Xartos** [comment]
Right, yea. That `inventory.ini` file are only there to give you a start if you set up this with bare metal machines. So basically just to give you a start. If you have your own inventory file (One that is created from terraform scrips) you should use that one instead.

Because we cant assume that you can use a dynamic terraform inventory if you have bare metal machines. So I don't think we should have that as default.

**Comment by lentzi90** [comment]
Makes sense! It would probably be enough to reword step 2 in [the quick start](https://github.com/elastisys/compliantkubernetes-kubespray#quick-start). That was where I got this from. If it mentioned that you may use dynamic inventories or tweak other settings as well it would be better. Now I understand it as I'm only supposed to edit the IPs and not touch anything else (and I must use that file).

**Comment by Xartos** [comment]
@lentzi90 Would you say that https://github.com/elastisys/compliantkubernetes-kubespray/pull/30 closes this issue?
Or would you like even more documentation on this?

**Comment by lentzi90** [comment]
Yes, #30 together with #22 is enough to close this I think. :slightly_smiling_face:  Closing...

**Comment by lentzi90** [comment]
Err... didn't realize #30 was not merged yet :joy:

**Comment by Xartos** [comment]
It is now :wink:
