### ISSUE TITLE
[3] Ingress configuration

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-kubespray#25]
We currently don't have anything regarding how the ingress-controller should be set up complientkubernetes-kubespray. What IP should one point DNS records at? Do we provide load balancers? What about security groups?

This will probably differ between cloud providers. To start with, we should investigate what the `contrib/terraform` code gives us for each cloud provider we are interested in.

Status so far:

- Openstack: security groups block access to 80/443 by default and no loadbalancers are created

Definition of done: There are instructions, default configuration or code that will give you a working kubespray cluster with ingress for each cloud provider we support.

Note: We may want to split this up into several tasks, one per cloud provider, maybe one for investigation, or similar.

**Comment by vanneback** [comment]
Update: exoscale works out of the box.  Dns records need to be pointed to the elastic IP of the worker nodes. This is some manual work (or scripts in our case) to set up dns.

**Comment by vanneback** [comment]
Update aws: An application load balancer need to be created with the following config:

* Same vpc as cluster
* Connected to the **public** subnets
* Listeners on port 80 (and 443 for https)
* If using https certificates will need to be created in aws
* A new security group allowing traffic on 80 and 443
* A target group with all the worker nodes.
* Health check on worker nodes on port 80 `/healthz`

The dns should then point to the LB address.

Im not sure how to include this in a good way? should we just add these steps in readme or try to upstream LB option in kubespray? The standard way of most documentation includes creating a public LB for each service and not use ingress like we want to. Another approach would be to use a ingress service instead of a ds but this is not an option in kubespray

**Comment by cristiklein** [comment]
@jakubkrzywda How did you deal with Ingress in AWS?

Kubespray is moving away from providing addons. Specifically, anything that is better supported via Helm Charts is deemed unfit for kubespray.

Regarding the various choices you mentioned, is there anything that we can add to the conversation that is not already known upstream? https://kubernetes.github.io/ingress-nginx/deploy/#aws

**Comment by lentzi90** [comment]
I think it would make sense for AWS to use the cloud provider integration and [configure the ingress controller to use a LoadBalancer Service](https://github.com/elastisys/compliantkubernetes-apps/blob/main/config/config/wc-config.yaml#L221).
Once the LoadBalancer is created we can then set up DNS for it.

**Comment by cristiklein** [comment]
Tough choice. For @jakubkrzywda 's case, it significantly simplifies everything to have `hostPort` Ingress controller, even on AWS. But in other cases, I agree that AWS's LB and it's integration with Kubernetes is preferred.

I'll think about it.

**Comment by vanneback** [comment]
> Update aws: An application load balancer need to be created with the following config:
> 
> * Same vpc as cluster
> * Connected to the **public** subnets
> * Listeners on port 80 (and 443 for https)
> * If using https certificates will need to be created in aws
> * A new security group allowing traffic on 80 and 443
> * A target group with all the worker nodes.
> * Health check on worker nodes on port 80 `/healthz`
> 
> The dns should then point to the LB address.
> 
> Im not sure how to include this in a good way? should we just add these steps in readme or try to upstream LB option in kubespray? The standard way of most documentation includes creating a public LB for each service and not use ingress like we want to. Another approach would be to use a ingress service instead of a ds but this is not an option in kubespray

This is no longer the way we should do this on AWS. It is supported out of the box when deploying kubernetes-apps with aws as init argument. This will use a service of type LoadBalancer connected to the ingress controller. This will automatically update security group rules etc. The dns should then be directed to the NLB used on the ingress controller

**Comment by llarsson** [comment]
I think [external-dns](https://github.com/kubernetes-sigs/external-dns) should be strongly evaluated when it comes to automating Ingress and Service DNS handling. It works great in AWS (where I have used it), and I have no reason to think it would not work equally great for the other supported DNS providers..

**Comment by cristiklein** [comment]
I use it on Azure in production. Never missed an update. :smile:

**Comment by llarsson** [comment]
I second the intuition that this can/should be broken up per cloud provider, expressed in the description of this issue. 

Otherwise, this is (a) a rather large issue to tackle and track and (b) a missed opportunity to parallelize the work that needs to be done (and thus get results faster).

Who would, process-wise, break this into sub-issues?

**Comment by llarsson** [comment]
And, related question, is the list of supported clouds exactly those that are in the image here: https://compliantkubernetes.io/compliance/ ?

**Comment by llarsson** [comment]
Closing because of https://github.com/elastisys/compliantkubernetes/pull/59
