### ISSUE TITLE
[1] Multiple clusters with dynamic inventory

### ISSUE THREAD

**Issue by lentzi90** [elastisys/compliantkubernetes-kubespray#31]
This can be seen as a subtask or replacement of https://github.com/elastisys/ck8s-ops/issues/57.

The [terraform code for openstack](https://github.com/kubernetes-sigs/kubespray/tree/master/contrib/terraform/openstack) among others, make use of a [python script for dynamic inventories](https://github.com/kubernetes-sigs/kubespray/blob/master/contrib/terraform/terraform.py).
This works well for a single cluster, but as soon as you try to set up a second, you will notice that it finds the terraform state of *all* clusters and tries to create one huge cluster instead of two separate.

The script works by searching for `*.tfstate` "below the working directory".
I'm not sure what exactly the working directory is when [using compliantkubernetes-kubespray](https://github.com/elastisys/compliantkubernetes-kubespray/blob/main/bin/apply.bash#L25), but for me at least it finds the state in both `sc-config` and `wc-config`, directly below my `$CK8S_CONFIG_PATH`.

Definition of done: It is possible to use compliantkubernetes-kubespray with multiple clusters using dynamic inventories.

**Comment by Xartos** [comment]
I guess this is a bug (or a lack of feature) in the kubespray code rather than a bug in our code.

And I'm not sure I see any benefits of having this dynamic inventory to a inventory generated by terraform. The dynamic inventory would still need to be refreshed to update it's content, which would be the same if you used the template route. And then you get a file that is easy to read and understandable. 

The dynamic inventory is however still a part of the openstack terraform code and I still think we should decide and document how to structure our config folders, but since we still might need more infrastructure (like lb's and things like that) I would not be against updating the openstack scripts upstream to support this.

**Comment by Xartos** [comment]
To set the "working directory" that the script will search for `tfvars` you can set the environment variable `TERRAFORM_STATE_ROOT`

**Comment by Xartos** [comment]
Suggested solution

export `TERRAFORM_STATE_ROOT` to config dir for the cluster for all ansible scripts (apply and run-playbook).
This shouldn't be an issue for clusters without dynamic inventories and it will make it work for clusters with dynamic inventories.
