### ISSUE TITLE
[3] Upgrade fails on etcdutl step

### ISSUE THREAD

**Issue by Ajarmar** [elastisys/compliantkubernetes-kubespray#337]
**Describe the bug**
The following step fails when running the `upgrade_cluster` playbook if the flag `--skip-tags=download` is used: https://github.com/kubernetes-sigs/kubespray/blob/v2.23.1/roles/etcdctl_etcdutl/tasks/main.yml#L23

The step is only run for master nodes.

**To Reproduce**

1. Run the kubespray upgrade for `v2.23` by following the guide.
2. When running `./bin/ck8s-kubespray run-playbook <sc|wc> upgrade_cluster.yml -b --skip-tags=download`, the user will receive an error on the master nodes:
  ```
  TASK [etcdctl_etcdutl : Copy etcd binary] **********************************************************
fatal: [<master-node-name>]: FAILED! => {"changed": false, "msg": "Source '/tmp/releases/etcd-v3.5.7-linux-amd64.tar.gz' does not exist"}
  ```

**Expected behavior**
No error should occur. It should be possible to run the download step and the rest of the upgrade separately.

**Version (add all relevant versions):**

- Compliant kubernetes kubespray v2.23.0-ck8s1 (when upgrading to this version)

**Additional context**
The reason why this fails is because, when using `etcd_deployment_type: kubeadm`, the file that the step is attempting to copy is not downloaded onto the node when running the `upgrade_cluster` playbook with the `--tags=download` flag separately (which we recommend in the migration guide).
The `etcdctl_etcdutl` role has a step to run the `download_file` role to download the file it tries to copy, but when running with `--skip-tags=download` this step is skipped - so the file will never be downloaded.

I have identified the following potential fixes to this:

- Use `-e skip_downloads=true` instead of `--skip-tags=download`. This should allow the `etcdctl_etcdutl` role to download the file, while skipping the "main" download. However, using this variable also causes other things to be skipped, such as `kubespray_defaults` and `kubernetes_preinstall`, so this must be tested to see that it works as expected. See this file: https://github.com/kubernetes-sigs/kubespray/blob/v2.23.1/playbooks/upgrade_cluster.yml#L26
- Make a change in kubespray to make sure the relevant file is downloaded even when using `etcd_deployment_type: kubeadm`.
- Use `etcd_deployment_type: host` instead of `kubeadm`. (I assume we use `kubeadm` for a reason, though.)

**Comment by Pavan-Gunda** [comment]
We do this next sprint if there is no traction to fix this upstream :)

**Comment by anders-elastisys** [comment]
I have looked into the proposed solutions and from my testing it should be safe to use the `-e skip_downloads=true` instead of `--skip-tags=download` for the disruptive part of the upgrade. The tasks that would be skipped in the `upgrade_cluster.yml` playbook are only for downloading files, and digging into all of the roles used by this playbook, I can not find anything that suggests that an upgrade would break when running with `-e skip_downloads=true` as long as you have prepared the nodes with the `--tags=download` flag beforehand, and testing showed the same results. However, some download steps that would usually be skipped when running with `--skip-tags=download` are not skipped when running with `-e skip_downloads=true` (e.g. the task `Containerd | Download containerd` runs twice, as there is no condition for `skip_downloads`).

> [!NOTE]
> Everything that is skipped in [this task](https://github.com/kubernetes-sigs/kubespray/blob/v2.23.1/playbooks/upgrade_cluster.yml#L26-L28) can be ignored, as these are only run if you have `download_run_once=true`, which is default false, and as this [downloads document](https://github.com/kubernetes-sigs/kubespray/blob/v2.23.1/docs/downloads.md) describes it, that task is only if you want to download in "pull once, push many" mode instead of downloading on each host which is how we currently do in our upgrades.

I also looked into changing the upgrade playbook so that it would download the etcd binary when running with `--tags=download`. And I found some solutions that worked fine, but I did not find a solution that avoided the file from being downloaded twice in the case that you are not running `upgrade-cluster.yml` with any additional flags.
However, I believe that some download tasks will always run twice when not providing flags for the `upgrade-cluster.yml` playbook, thus, this might not be a problem (see example below showing logs from running the upgrade playbook without `tags` flags, where the same containerd file is "downloaded" twice during different tasks).

```console
TASK [download : Download_file | Starting download of file] ********************************************************************************************************************************
ok: [sc-k8s-control-plane-1] => {
    "msg": "https://github.com/containerd/containerd/releases/download/v1.7.6/containerd-1.7.6-linux-amd64.tar.gz"
}
Wednesday 03 January 2024  08:59:29 +0000 (0:00:00.022)       0:01:27.604 *****
...

TASK [container-engine/containerd : Download_file | Starting download of file] *************************************************************************************************************
ok: [sc-k8s-control-plane-1] => {
    "msg": "https://github.com/containerd/containerd/releases/download/v1.7.6/containerd-1.7.6-linux-amd64.tar.gz"
}
Wednesday 03 January 2024  09:01:18 +0000 (0:00:00.395)       0:03:15.821 *****
```

When it comes to the third suggestion, changing `etcd_deployment_type` from `kubeadm` to `host` would change so that etcd runs as a daemonset on the nodes instead of running as static pods as part of the kubernetes cluster. I am not sure about the reason for why we run it as we do now, but I feel like we probably do not want to change this setting. I can see having etcd continue running in the cluster to be easier to monitor and debug.

To proceed, I would be happy to go through my solutions before potentially doing any upstreaming to the Kubespray repo and see what solution we would prefer.

**Comment by Ajarmar** [comment]
Great investigation. Personally I feel like using `-e skip_downloads=true` is closer to the "intended" use case than using `--skip-tags=download`, so I'd be fine with just going with the first solution. It could be nice to implement the second solution as well, but I'm worried that using `--skip-tags=download` could break again in the future if it's not a use case the kubespray developers test for.

**Comment by anders-elastisys** [comment]
Thanks @Ajarmar, I will proceed by updating the upgrade docs then.
